export const ADDING_RECIPE_SET_MENU = 'ADDING_RECIPE_SET_MENU';
export const ADDING_RECIPE_UNSET_MENU = 'ADDING_RECIPE_UNSET_MENU';
export const ADDING_RECIPE_SET_SELECTED_RECIPE = 'ADDING_RECIPE_SET_SELECTED_RECIPE';