
export const USER_SET = 'USER_SET'
export const USER_UNSET = 'USER_UNSET'
export const USER_LOGIN_REQUESTING = 'USER_LOGIN_REQUESTING'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_REJECT = 'USER_LOGIN_REJECT'
